version: "3.1"

volumes:
    volume_mysql_data:

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - LANG=C.UTF-8
    networks:
      -  mysql-network
    volumes:
      - volume_mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8085:8080
    networks:
      -  mysql-network

networks:
  mysql-network:
    driver: bridge
